POST http://localhost:3000/api/confirm-pickup

{
  "dateAndTime": "2022-01-01T00:00:00.000Z",
  "deliveryOption": "Direct Handoff",
  "price": {
    "name": "Bronze",
    "price": 1099,
    "itemId": "123"
  },
  "confirmPickUp": {
    "subscriptionItem": {
      "itemId": "456",
      "itemName": "Subscription",
      "quantity": 1
    },
    "packageItem": {
      "itemId": "789",
      "itemName": "Package",
      "quantity": 2
    },
    "expiryDate": {
      "orderDate": "2022-01-01T00:00:00.000Z",
      "subscription": "Bronze"
    },
    "calculateCost": {
      "subscription": "Bronze",
      "packages": 2
    }
  },
  "image": "image.jpg",
  "orderConfirmation": {
    "order_number": "123",
    "order_date": "2022-01-01T00:00:00.000Z",
    "order_status": "Driver received",
    "name": "John Doe",
    "orderRef": "456",
    "email": "john@example.com",
    "location": "123 Main St",
    "cardType": "Visa",
    "cardNumber": 1234,
    "paymentSuccessful": true,
    "order_details": {
      "total_cost": 1099,
      "pickup_date": "2022-01-01T00:00:00.000Z",
      "pickup_method": "Direct Handoff",
      "total_packages": 2,
      "extra_packages_included": 1,
      "promo_code": "",
      "pickup_details": {
        "address_id": "123",
        "contact_full_name": "John Doe",
        "contact_phone_number": 1234567890,
        "unit_number": 1,
        "street": "Main St",
        "city": "Anytown",
        "province": "ON",
        "country": "Canada",
        "postal_code": "A1B 2C3",
        "instructions": "Leave at the front door"
      }
    }
  }
}
